// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL2q-6fcA_El8_9btH9QHbansLoTKO-HA',
    appId: '1:783730760736:android:19b53e114cadb66d8ff045',
    messagingSenderId: '783730760736',
    projectId: 'fir-app-f6a15',
    databaseURL: 'https://fir-app-f6a15-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-f6a15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDIW_z6naA6LjGO0xn89lyz0zVG-z7PF8',
    appId: '1:783730760736:ios:0159a6ac576fe3da8ff045',
    messagingSenderId: '783730760736',
    projectId: 'fir-app-f6a15',
    databaseURL: 'https://fir-app-f6a15-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-f6a15.firebasestorage.app',
    iosClientId: '783730760736-2kkvq1r28d4gs5k0nq2rv04fmg8k5kmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.itiTraining',
  );

}